# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Clean up container on manual event
on:
  workflow_dispatch:
    inputs:
      node:
        default: "rocm"
        description: "Hardware to clean"
        required: true
        type: string
      clean_list:
        default: ""
        description: "docker command to clean"
        required: false
        type: string

permissions:
  contents: read

jobs:
  clean:
    runs-on: "${{ inputs.node }}"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Clean up container
        run: |
          docker ps
          if [ "${{ inputs.clean_list }}" ]; then
            echo "----------stop and remove containers----------"
            docker stop ${{ inputs.clean_list }} && docker rm ${{ inputs.clean_list }}
            echo "----------container removed----------"
            docker ps
          fi
