# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Check Duplicated Images

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, ready_for_review, synchronize]
    paths:
      - "**/docker_image_build/*.yaml"
      - ".github/workflows/pr-check-duplicated-image.yml"
      - ".github/workflows/scripts/check_duplicated_image.py"
  workflow_dispatch:

# If there is a new commit, the previous jobs will be canceled
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-duplicated-image:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Clean Up Working Directory
        run: sudo rm -rf ${{github.workspace}}/*

      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check all the docker image build files
        run: |
          pip install PyYAML
          cd ${{github.workspace}}
          build_files=""
          for f in `find . -path "*/docker_image_build/build.yaml"`; do
              build_files="$build_files $f"
          done
          python3 .github/workflows/scripts/check_duplicated_image.py $build_files
        shell: bash
