# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Check the validity of links in docker_images_list.

on:
  push:
    branches: [main]
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  contents: read

jobs:
  check-dockerfile-paths:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Clean Up Working Directory
        run: sudo rm -rf ${{github.workspace}}/*

      - name: Checkout repo GenAIExamples
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check the validity of links
        run: |
          cd ${{github.workspace}}
          miss="FALSE"
          while IFS=: read -r line link; do
            http_status=$(curl -o /dev/null -s -w "%{http_code}" "$link")
            if [ "$http_status" -eq 200 ]; then
              echo "Valid link: $link (Line $line)"
            else
              echo "Broken link: $link (Line $line) (Status $http_status) "
              echo "-----------------retry strat----------------------"
              retry_http_status=$(curl -o /dev/null -s -w "%{http_code}" "$link")
              if [ "$retry_http_status" -eq 200 ]; then
                miss="FALSE"
                echo "Valid link: $link (Line $line)"
                echo "---------------Retry is valid---------------------"
              else
                miss="TRUE"
                echo "Retry broken link: $link (Line $line) (Status $http_status) "
                echo "-------------Retry is not valid-------------------"
              fi
            fi
          done < <(grep -n -oP '(?<=a href=")[^"]*(?=">)' ../../docker_images_list.md)

          if [[ "$miss" == "TRUE" ]]; then
            exit 1
          fi
        shell: bash
